# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: bdd-gh-1587135049
  repository: file://../bdd-gh-1587135049
